Switch actions to particular revisions and fix build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,18 +17,18 @@ jobs:
       cancel-in-progress: true
 
     steps:
-    - uses: actions/checkout@v4
+    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
 
     # build the doxygen XML for breathe
     - name: Checkout openchemistry
-      uses: actions/checkout@v4
+      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
       with:
         repository: openchemistry/openchemistry
         submodules: recursive
         path: openchemistry
 
     - name: Checkout openchemistry and avogadrolibs
-      uses: actions/checkout@v4
+      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
       with:
         repository: openchemistry/avogadrolibs
         path: openchemistry/avogadrolibs
@@ -36,16 +36,16 @@ jobs:
     - name: Install packages
       run: |
         sudo apt-get -qq update
-        sudo apt-get -qq install doxygen ninja-build libeigen3-dev libglew-dev libxml2-dev
+        sudo apt-get -qq install doxygen graphviz ninja-build libeigen3-dev libglew-dev libxml2-dev
 
     - name: Install uv
-      uses: astral-sh/setup-uv@v2
+      uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
       with:
         enable-cache: true
         cache-dependency-glob: "uv.lock"
 
     - name: Set up Python
-      uses: actions/setup-python@v5
+      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
       with:
         python-version-file: ".python-version"
 
@@ -53,7 +53,7 @@ jobs:
       run: uv sync
 
     - name: Install Qt
-      uses: jurplel/install-qt-action@v4
+      uses: jurplel/install-qt-action@d325aaf2a8baeeda41ad0b5d39f84a6af9bcf005 # v4.3.0
 
     - name: Configure
       run: |
@@ -65,7 +65,7 @@ jobs:
 
     - name: Build doxygen
       run: |
-        ninja
+        ninja || true # might fail with warnings
         cd avogadrolibs
         ninja documentation
       shell: bash
@@ -81,10 +81,11 @@ jobs:
 
     - name: Setup tmate session
       if: ${{ failure() }}
-      uses: mxschmitt/action-tmate@v3
+      uses: mxschmitt/action-tmate@7b6a61a73bbb9793cb80ad69b8dd8ac19261834c # v3.22
+      timeout-minutes: 30
 
     - name: Deploy to gh-pages
-      uses: peaceiris/actions-gh-pages@v3
+      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
       # If you're changing the branch from main,
       # also change the `main` in `refs/heads/main`
       # below accordingly.
